### ISSUE TITLE
Syntax bug

### ISSUE THREAD

**Issue by poodineh** [meysamhadeli/University-Microservices#1]
Make this bug fix:

BuildingBlocks -> CAP -> extensions.cs
add brackets {} for namespace BuildingBlocks.CAP block

**Comment by poodineh** [comment]
Do the same for the followings:

Cources/University.cources.infrastructure/extensions.cs
Students/University.cources.infrastructure/extensions.cs

**Comment by meysamhadeli** [comment]
> Make this bug fix:
> 
> BuildingBlocks -> CAP -> extensions.cs add brackets {} for namespace BuildingBlocks.CAP block

Hi.
Its new syntax `file-scoped namespaces` in c#10.
